// Copyright 2024 Octopus Project
// Licensed under Apache License 2.0

// Package types contains shared types used across all Octopus packages
package types

import (
	"bytes"
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/binary"
	"encoding/json"
	"sync"
	"time"
)

// PublicKey is an Ed25519 public key
type PublicKey = ed25519.PublicKey

// PrivateKey is an Ed25519 private key
type PrivateKey = ed25519.PrivateKey

// Signature is an Ed25519 signature
type Signature []byte

// Hash is a SHA256 hash
type Hash [32]byte

// Phase represents the phase in Pipelined HotStuff
type Phase int

const (
	PhasePrepare Phase = iota
	PhasePrecommit
	PhaseCommit
	PhaseDecide
)

func (p Phase) String() string {
	switch p {
	case PhasePrepare:
		return "PREPARE"
	case PhasePrecommit:
		return "PRECOMMIT"
	case PhaseCommit:
		return "COMMIT"
	case PhaseDecide:
		return "DECIDE"
	default:
		return "UNKNOWN"
	}
}

// TxType represents the type of transaction
type TxType int

const (
	TxTypeNormal TxType = iota
	TxTypeReconfig
)

// ReconfigType represents the type of reconfiguration
type ReconfigType int

const (
	ReconfigJoin ReconfigType = iota
	ReconfigLeave
	ReconfigAutoLeave // Hydra auto-transition leave (generated by quorum vote, not user request)
)

// ReconfigData represents the payload for a reconfiguration transaction
type HydraAutoVote struct {
	SenderID  uint64    `json:"sender_id"`
	Signature Signature `json:"signature,omitempty"`
	Digest    []byte    `json:"digest,omitempty"`
}

type HydraTransitionProof struct {
	View        uint64                   `json:"view"`
	NewConfigID uint64                   `json:"new_config_id"`
	Leaves      []uint64                 `json:"leaves,omitempty"`
	BlockHash   []byte                   `json:"block_hash,omitempty"`
	AutoVotes   map[uint64]*HydraAutoVote `json:"auto_votes,omitempty"`
}

// ReconfigData represents the payload for a reconfiguration transaction
// Manual join/leave requests are individually signed by the requester.
// Auto-leave requests are authenticated by a Hydra quorum proof.
type ReconfigData struct {
	Type           ReconfigType
	NodeID         uint64
	PublicKey      PublicKey
	VRFPublicKey   []byte
	Power          uint64
	Epoch          uint64
	TargetEpoch    uint64
	Signature      Signature
	AutoLeaveProof *HydraTransitionProof
}

func ReconfigSigningBytes(data *ReconfigData) []byte {
	if data == nil {
		return nil
	}
	type reconfigSigningData struct {
		Type         ReconfigType `json:"type"`
		NodeID       uint64       `json:"node_id"`
		PublicKey    []byte       `json:"public_key,omitempty"`
		VRFPublicKey []byte       `json:"vrf_public_key,omitempty"`
		Power        uint64       `json:"power"`
		Epoch        uint64       `json:"epoch"`
		TargetEpoch  uint64       `json:"target_epoch"`
	}
	payload, _ := json.Marshal(reconfigSigningData{
		Type:         data.Type,
		NodeID:       data.NodeID,
		PublicKey:    append([]byte(nil), data.PublicKey...),
		VRFPublicKey: append([]byte(nil), data.VRFPublicKey...),
		Power:        data.Power,
		Epoch:        data.Epoch,
		TargetEpoch:  data.TargetEpoch,
	})
	return payload
}

func (d *ReconfigData) Sign(privateKey PrivateKey) {
	if d == nil {
		return
	}
	d.Signature = ed25519.Sign(privateKey, ReconfigSigningBytes(d))
}

func (d *ReconfigData) VerifySignature() bool {
	if d == nil {
		return false
	}
	switch d.Type {
	case ReconfigJoin, ReconfigLeave:
		return ed25519.Verify(d.PublicKey, ReconfigSigningBytes(d), d.Signature)
	default:
		return false
	}
}

// Transaction represents a transaction
type Transaction struct {
	Type    TxType
	Payload []byte // Normal: data, Reconfig: serialized ReconfigData
}

// Block represents a block in the DAG
type Block struct {
	mu sync.RWMutex

	// Core fields
	Height uint64
	Hash   []byte
	Parent []byte
	Data   []byte

	JoinRequests  []PublicKey
	LeaveRequests []PublicKey

	// Payload (Changed from Txs to VertexCertificates for Multi-Leader)
	Payload []*VertexCertificate

	// Pipelined fields
	View  uint64
	Phase Phase
	Epoch uint64 // Epoch this block belongs to

	// Multi-Leader fields
	LeaderID uint64
	Rank     int64
	LaneID   uint64
	ConfigID uint64

	// QC
	Justify *QuorumCertificate

	// TC: Timeout Certificate from the previous view (present when the
	// previous leader timed out and liveness required TC-based view advance)
	TimeoutCert *TimeoutCertificate

	// Metadata
	Timestamp int64

	// Phase 5: Random Beacon (Seed for next view/epoch)
	Randomness []byte
}

// NewBlock creates a new block
func NewBlock(height uint64, parent []byte, data []byte, view uint64, epoch uint64, leaderID uint64, rank int64, justify *QuorumCertificate, randomness []byte) *Block {
	block := &Block{
		Height:     height,
		Parent:     parent,
		Data:       data,
		View:       view,
		Epoch:      epoch,
		Phase:      PhasePrepare,
		LeaderID:   leaderID,
		Rank:       rank,
		Justify:    justify,
		Payload:    make([]*VertexCertificate, 0),
		Timestamp:  time.Now().UnixNano(),
		Randomness: randomness,
	}
	block.Hash = block.ComputeHash()
	return block
}

func (b *Block) ComputeHash() []byte {
	payloadCap := 0
	for _, cert := range b.Payload {
		if cert != nil {
			payloadCap += len(cert.VertexHash) + 16
		}
	}
	buffer := make([]byte, 0, 128+len(b.Parent)+len(b.Data)+len(b.Randomness)+payloadCap)
	u64 := make([]byte, 8)
	i64 := make([]byte, 8)

	binary.BigEndian.PutUint64(u64, b.Height)
	buffer = append(buffer, u64...)
	buffer = append(buffer, b.Parent...)
	buffer = append(buffer, b.Data...)

	binary.BigEndian.PutUint64(u64, b.View)
	buffer = append(buffer, u64...)
	binary.BigEndian.PutUint64(u64, b.Epoch)
	buffer = append(buffer, u64...)
	binary.BigEndian.PutUint64(u64, b.LeaderID)
	buffer = append(buffer, u64...)
	binary.BigEndian.PutUint64(i64, uint64(b.Rank))
	buffer = append(buffer, i64...)
	binary.BigEndian.PutUint64(u64, b.LaneID)
	buffer = append(buffer, u64...)
	binary.BigEndian.PutUint64(u64, b.ConfigID)
	buffer = append(buffer, u64...)
	binary.BigEndian.PutUint64(i64, uint64(b.Timestamp))
	buffer = append(buffer, i64...)
	buffer = append(buffer, b.Randomness...)

	if b.Justify != nil {
		buffer = append(buffer, b.Justify.BlockHash...)
		binary.BigEndian.PutUint64(u64, b.Justify.View)
		buffer = append(buffer, u64...)
		binary.BigEndian.PutUint64(u64, b.Justify.Epoch)
		buffer = append(buffer, u64...)
	}

	binary.BigEndian.PutUint64(u64, uint64(len(b.Payload)))
	buffer = append(buffer, u64...)
	for _, cert := range b.Payload {
		if cert == nil {
			binary.BigEndian.PutUint64(u64, 0)
			buffer = append(buffer, u64...)
			continue
		}
		buffer = append(buffer, cert.VertexHash[:]...)
		binary.BigEndian.PutUint64(u64, cert.Epoch)
		buffer = append(buffer, u64...)
		binary.BigEndian.PutUint64(u64, cert.Round)
		buffer = append(buffer, u64...)
	}

	hash := sha256.Sum256(buffer)
	return hash[:]
}

// GetHash returns the block hash
func (b *Block) GetHash() []byte {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.Hash
}

// GetParent returns the parent block hash
func (b *Block) GetParent() []byte {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.Parent
}

// GetView returns the view number
func (b *Block) GetView() uint64 {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.View
}

// GetEpoch returns the epoch number
func (b *Block) GetEpoch() uint64 {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.Epoch
}

// GetHeight returns the block height
func (b *Block) GetHeight() uint64 {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.Height
}

// GetLeaderID returns the leader ID
func (b *Block) GetLeaderID() uint64 {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.LeaderID
}

func (b *Block) GetLaneID() uint64 {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.LaneID
}

func (b *Block) GetConfigID() uint64 {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.ConfigID
}

// GetRank returns the global ordering rank
func (b *Block) GetRank() int64 {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.Rank
}

// GetPhase returns the current phase
func (b *Block) GetPhase() Phase {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.Phase
}

// SetPhase sets the block phase
func (b *Block) SetPhase(phase Phase) {
	b.mu.Lock()
	defer b.mu.Unlock()
	b.Phase = phase
}

func (b *Block) GetJoinRequests() []PublicKey {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.JoinRequests
}

func (b *Block) GetLeaveRequests() []PublicKey {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.LeaveRequests
}

// QuorumCertificate represents a quorum certificate
type QuorumCertificate struct {
	mu sync.RWMutex

	BlockHash []byte
	View      uint64
	Epoch     uint64 // Epoch this QC belongs to
	ConfigID  uint64
	Lane      uint64
	Phase     Phase

	// Signatures from validators
	Signatures map[uint64][]byte

	// Aggregated signature
	AggregatedSig []byte

	// Number of signatures
	NumSignatures int
}

// NewQuorumCertificate creates a new QC
func NewQuorumCertificate(blockHash []byte, view uint64, epoch uint64, phase Phase) *QuorumCertificate {
	return NewQuorumCertificateWithIdentity(blockHash, view, epoch, epoch, 0, phase)
}

func NewQuorumCertificateWithIdentity(blockHash []byte, view uint64, epoch uint64, configID uint64, lane uint64, phase Phase) *QuorumCertificate {
	return &QuorumCertificate{
		BlockHash:  blockHash,
		View:       view,
		Epoch:      epoch,
		ConfigID:   configID,
		Lane:       lane,
		Phase:      phase,
		Signatures: make(map[uint64][]byte),
	}
}

// AddSignature adds a signature to the QC
func (qc *QuorumCertificate) AddSignature(validatorID uint64, signature []byte) {
	qc.mu.Lock()
	defer qc.mu.Unlock()
	if _, exists := qc.Signatures[validatorID]; !exists {
		qc.Signatures[validatorID] = signature
		qc.NumSignatures++
	}
}

// GetBlockHash returns the block hash
func (qc *QuorumCertificate) GetBlockHash() []byte {
	qc.mu.RLock()
	defer qc.mu.RUnlock()
	return qc.BlockHash
}

// GetView returns the view
func (qc *QuorumCertificate) GetView() uint64 {
	qc.mu.RLock()
	defer qc.mu.RUnlock()
	return qc.View
}

// GetEpoch returns the epoch
func (qc *QuorumCertificate) GetEpoch() uint64 {
	qc.mu.RLock()
	defer qc.mu.RUnlock()
	return qc.Epoch
}

// GetNumSignatures returns the number of signatures
func (qc *QuorumCertificate) GetNumSignatures() int {
	qc.mu.RLock()
	defer qc.mu.RUnlock()
	return qc.NumSignatures
}

// IsComplete checks if the QC has enough signatures
func (qc *QuorumCertificate) IsComplete(quorumSize uint64) bool {
	qc.mu.RLock()
	defer qc.mu.RUnlock()
	return uint64(qc.NumSignatures) >= quorumSize
}

// Message represents a network message
type Message struct {
	Type          MessageType
	SenderID      uint64
	View          uint64
	Epoch         uint64
	ConfigID      uint64
	Lane          uint64
	LeaderSetHash []byte
	BarrierView   uint64
	Instance      uint64
	Height        uint64
	Data          []byte
	Block         *Block
	Vote          *Vote
	QC            *QuorumCertificate
	TC            *TimeoutCertificate
	TimeoutVote   *TimeoutVote
	Signature     Signature
}

// MessageType represents the type of message
type MessageType int

const (
	MsgProposal MessageType = iota
	MsgVote
	MsgNewView
	MsgTimeout // Timeout vote for TC aggregation
	MsgJoin
	MsgLeave
	MsgSync
)

func (mt MessageType) String() string {
	switch mt {
	case MsgProposal:
		return "PROPOSAL"
	case MsgVote:
		return "VOTE"
	case MsgNewView:
		return "NEW_VIEW"
	case MsgTimeout:
		return "TIMEOUT"
	case MsgJoin:
		return "JOIN"
	case MsgLeave:
		return "LEAVE"
	case MsgSync:
		return "SYNC"
	default:
		return "UNKNOWN"
	}
}

// Validator represents a validator in the network
type Validator struct {
	ID           uint64
	PublicKey    PublicKey
	VRFPublicKey []byte
	Power        uint64
	IsActive     bool
}

type Configuration struct {
	ID         uint64
	Validators map[uint64]*Validator
	QuorumSize uint64
}

func (c *Configuration) Hash() []byte {
	if c == nil {
		return nil
	}
	type validatorHash struct {
		ID           uint64 `json:"id"`
		PublicKey    []byte `json:"public_key"`
		VRFPublicKey []byte `json:"vrf_public_key,omitempty"`
		Power        uint64 `json:"power"`
		IsActive     bool   `json:"is_active"`
	}
	items := make([]validatorHash, 0, len(c.Validators))
	for id, v := range c.Validators {
		if v == nil {
			continue
		}
		items = append(items, validatorHash{
			ID:           id,
			PublicKey:    append([]byte(nil), v.PublicKey...),
			VRFPublicKey: append([]byte(nil), v.VRFPublicKey...),
			Power:        v.Power,
			IsActive:     v.IsActive,
		})
	}
	for i := 0; i < len(items); i++ {
		for j := i + 1; j < len(items); j++ {
			if items[j].ID < items[i].ID {
				items[i], items[j] = items[j], items[i]
			}
		}
	}
	payload, _ := json.Marshal(struct {
		ID         uint64          `json:"id"`
		QuorumSize uint64          `json:"quorum_size"`
		Validators []validatorHash `json:"validators"`
	}{
		ID:         c.ID,
		QuorumSize: c.QuorumSize,
		Validators: items,
	})
	sum := sha256.Sum256(payload)
	return sum[:]
}

func (c *Configuration) ToValidatorSet() *ValidatorSet {
	if c == nil {
		return nil
	}
	validators := make(map[uint64]*Validator, len(c.Validators))
	for id, v := range c.Validators {
		if v == nil {
			continue
		}
		dup := *v
		if v.PublicKey != nil {
			dup.PublicKey = append(PublicKey(nil), v.PublicKey...)
		}
		if v.VRFPublicKey != nil {
			dup.VRFPublicKey = append([]byte(nil), v.VRFPublicKey...)
		}
		validators[id] = &dup
	}
	valSet := NewValidatorSet(c.ID, validators)
	valSet.QuorumSize = c.QuorumSize
	return valSet
}

type ConfigQC struct {
	Epoch         uint64
	ConfigHash    []byte
	Signatures    map[uint64][]byte
	NumSignatures int
}

type EpochTransition struct {
	OldEpoch         uint64   `json:"old_epoch"`
	NewEpoch         uint64   `json:"new_epoch"`
	ActivationHeight uint64   `json:"activation_height"`
	ActivationRank   uint64   `json:"activation_rank"`
	Added            []uint64 `json:"added,omitempty"`
	Removed          []uint64 `json:"removed,omitempty"`
	QuorumSize       uint64   `json:"quorum_size"`
	ConfigHash       []byte   `json:"config_hash,omitempty"`
}

// TimeoutVote is broadcast by a node when its view timer expires.
// Collecting 2f+1 TimeoutVotes for the same view forms a TimeoutCertificate.
type TimeoutVote struct {
	View      uint64
	Epoch     uint64
	ConfigID  uint64
	Lane      uint64
	VoterID   uint64
	HighestQC *QuorumCertificate // The voter's highest known QC
	Signature []byte
}

// TimeoutCertificate is an aggregated proof that 2f+1 nodes have timed out
// on the same view. It enables the next leader to safely propose without
// waiting for the previous view's QC (liveness under Byzantine leaders).
type TimeoutCertificate struct {
	View       uint64
	Epoch      uint64
	ConfigID   uint64
	Lane       uint64
	HighestQC  *QuorumCertificate // The highest QC among all timeout voters
	Signatures map[uint64][]byte  // voterID -> signature
	NumVoters  int
}

type JoinRequest struct {
	ID        uint64
	PublicKey PublicKey
	Power     uint64
	View      uint64
}

type LeaveRequest struct {
	ID        uint64
	PublicKey PublicKey
	View      uint64
}

// ValidatorSet represents a set of validators for a specific epoch
type ValidatorSet struct {
	Epoch      uint64
	Validators map[uint64]*Validator
	TotalPower uint64
	QuorumSize uint64
}

// NewValidatorSet creates a new validator set.
// TotalPower is computed by summing the Power of active validators only,
// ensuring correct quorum thresholds when validators have varying weights
// or some are marked inactive.
func NewValidatorSet(epoch uint64, validators map[uint64]*Validator) *ValidatorSet {
	var totalPower uint64
	for _, v := range validators {
		if v != nil && v.IsActive {
			p := v.Power
			if p == 0 {
				p = 1 // default power for active validators without explicit weight
			}
			totalPower += p
		}
	}
	if totalPower == 0 {
		// Fallback: if no validator has IsActive set (e.g., during bootstrap),
		// count all validators with unit power to avoid zero quorum.
		totalPower = uint64(len(validators))
	}
	quorumSize := totalPower*2/3 + 1

	return &ValidatorSet{
		Epoch:      epoch,
		Validators: validators,
		TotalPower: totalPower,
		QuorumSize: quorumSize,
	}
}

// Copy returns a deep copy of the ValidatorSet
func (vs *ValidatorSet) Copy() *ValidatorSet {
	if vs == nil {
		return nil
	}
	newValidators := make(map[uint64]*Validator, len(vs.Validators))
	for k, v := range vs.Validators {
		copied := *v
		if v.PublicKey != nil {
			copied.PublicKey = make(PublicKey, len(v.PublicKey))
			copy(copied.PublicKey, v.PublicKey)
		}
		if v.VRFPublicKey != nil {
			copied.VRFPublicKey = append([]byte(nil), v.VRFPublicKey...)
		}
		newValidators[k] = &copied
	}
	return &ValidatorSet{
		Epoch:      vs.Epoch,
		Validators: newValidators,
		TotalPower: vs.TotalPower,
		QuorumSize: vs.QuorumSize,
	}
}

func (vs *ValidatorSet) Hash() []byte {
	if vs == nil {
		return nil
	}
	cfg := &Configuration{
		ID:         vs.Epoch,
		Validators: vs.Validators,
		QuorumSize: vs.QuorumSize,
	}
	return cfg.Hash()
}

func VoteSigningBytes(blockID Hash, view uint64, epoch uint64, configID uint64, lane uint64) []byte {
	buf := make([]byte, 0, len(blockID)+32)
	tmp := make([]byte, 8)

	buf = append(buf, blockID[:]...)
	binary.BigEndian.PutUint64(tmp, view)
	buf = append(buf, tmp...)
	binary.BigEndian.PutUint64(tmp, epoch)
	buf = append(buf, tmp...)
	binary.BigEndian.PutUint64(tmp, configID)
	buf = append(buf, tmp...)
	binary.BigEndian.PutUint64(tmp, lane)
	buf = append(buf, tmp...)
	return buf
}

func QCSigningBytes(blockHash []byte, view uint64, epoch uint64, configID uint64, lane uint64) []byte {
	var blockID Hash
	copy(blockID[:], blockHash)
	return VoteSigningBytes(blockID, view, epoch, configID, lane)
}

func TimeoutSigningBytes(view uint64, epoch uint64, configID uint64, lane uint64) []byte {
	buf := make([]byte, 0, 32)
	tmp := make([]byte, 8)

	binary.BigEndian.PutUint64(tmp, view)
	buf = append(buf, tmp...)
	binary.BigEndian.PutUint64(tmp, epoch)
	buf = append(buf, tmp...)
	binary.BigEndian.PutUint64(tmp, configID)
	buf = append(buf, tmp...)
	binary.BigEndian.PutUint64(tmp, lane)
	buf = append(buf, tmp...)
	return buf
}

func LeaderSetHashEqual(left []byte, right []byte) bool {
	return bytes.Equal(left, right)
}

// Keypair represents a node's key pair
type Keypair struct {
	PublicKey  PublicKey
	PrivateKey PrivateKey
}
