#!/usr/bin/env python3
"""
Evolv-BFT — Configuration Generator

Generates peer maps and CLI arguments for N Evolv-BFT nodes across three
deployment modes:

  --k8s         Kubernetes (headless service DNS)
  --compose     Docker Compose (container names)
  --hosts FILE  Bare-metal (reads host IPs from file, one per line)

Usage examples:
  # Kubernetes — 1000 nodes
  python generate_config.py --nodes 1000 --k8s --manifest ./configs/genesis.json --output-dir ./configs

  # Docker Compose — 4 nodes for local testing
  python generate_config.py --nodes 4 --compose --manifest ./configs/genesis.json --output-dir ./configs

  # Bare metal — reads IPs from hosts.txt
  python generate_config.py --nodes 10 --hosts hosts.txt --manifest ./configs/genesis.json --output-dir ./configs
"""

import argparse
import ipaddress
import json
import sys
from pathlib import Path


# ── Defaults ────────────────────────────────────────────────────────────────
DEFAULT_P2P_PORT = 8080
DEFAULT_HTTP_PORT = 9000
DEFAULT_INSTANCES = 5
DEFAULT_BATCH_TXS = 2048
DEFAULT_TIMEOUT_MS = 1000
DEFAULT_INBOUND_MSG_QUEUE = 4096
DEFAULT_INBOUND_TX_QUEUE = 32768
DEFAULT_ORDERER_PENDING_CAP = 32768
DEFAULT_CONSENSUS_TOPIC = "evolvbft-consensus"
K8S_HEADLESS_SVC = "evolvbft-headless.default.svc.cluster.local"


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Generate Evolv-BFT configuration for N nodes.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--nodes", "-n", type=int, required=True, help="Total number of nodes"
    )
    p.add_argument(
        "--initial-validators",
        type=int,
        default=None,
        help="Initial validators (defaults to --nodes)",
    )
    p.add_argument(
        "--base-port",
        type=int,
        default=DEFAULT_P2P_PORT,
        help=f"Base P2P port (default {DEFAULT_P2P_PORT})",
    )
    p.add_argument(
        "--http-base-port",
        type=int,
        default=DEFAULT_HTTP_PORT,
        help=f"Base HTTP port (default {DEFAULT_HTTP_PORT})",
    )
    p.add_argument(
        "--instances",
        type=int,
        default=DEFAULT_INSTANCES,
        help=f"Parallel consensus instances (default {DEFAULT_INSTANCES})",
    )
    p.add_argument(
        "--batch-txs",
        type=int,
        default=DEFAULT_BATCH_TXS,
        help=f"Max TXs per batch (default {DEFAULT_BATCH_TXS})",
    )
    p.add_argument(
        "--timeout-ms",
        type=int,
        default=DEFAULT_TIMEOUT_MS,
        help=f"Pacemaker timeout ms (default {DEFAULT_TIMEOUT_MS})",
    )
    p.add_argument(
        "--output-dir",
        "-o",
        type=str,
        default="./configs",
        help="Output directory for generated configs",
    )
    p.add_argument(
        "--manifest",
        type=str,
        default="",
        help="Path to a genesis manifest generated by evolvbft-genesis (required for multi-node clusters)",
    )

    # Deployment mode (mutually exclusive)
    mode = p.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--k8s", action="store_true", help="Kubernetes mode — use headless service DNS"
    )
    mode.add_argument(
        "--compose",
        action="store_true",
        help="Docker Compose mode — use container names",
    )
    mode.add_argument(
        "--hosts",
        type=str,
        metavar="FILE",
        help="Bare-metal mode — read host IPs from file",
    )

    # Optional overrides
    p.add_argument(
        "--k8s-namespace",
        type=str,
        default="default",
        help="Kubernetes namespace (default: default)",
    )
    p.add_argument(
        "--k8s-svc-name",
        type=str,
        default="evolvbft-headless",
        help="Kubernetes headless service name",
    )
    p.add_argument(
        "--compose-prefix",
        type=str,
        default="evolvbft-node",
        help="Docker Compose container name prefix",
    )

    return p.parse_args()


def resolve_address(
    node_id: int, args: argparse.Namespace, host_list: list[str] | None
) -> tuple[str, int, int]:
    """Return (hostname, p2p_port, http_port) for a node."""
    if args.k8s:
        svc = f"{args.k8s_svc_name}.{args.k8s_namespace}.svc.cluster.local"
        hostname = f"evolvbft-{node_id}.{svc}"
        return hostname, args.base_port, args.http_base_port

    if args.compose:
        hostname = f"{args.compose_prefix}-{node_id}"
        return hostname, args.base_port, args.http_base_port

    # Bare-metal: unique ports on each host
    if host_list is None:
        raise RuntimeError("host_list required for bare-metal mode")
    host = host_list[node_id % len(host_list)]
    offset = node_id // len(host_list)
    p2p_port = args.base_port + offset
    http_port = args.http_base_port + offset
    return host, p2p_port, http_port


def load_manifest(path: str) -> dict | None:
    if not path:
        return None
    manifest_path = Path(path)
    if not manifest_path.is_file():
        raise FileNotFoundError(f"manifest not found: {path}")
    with open(manifest_path, encoding="utf-8") as f:
        manifest = json.load(f)
    nodes = manifest.get("nodes", [])
    manifest["nodes_by_id"] = {int(node["id"]): node for node in nodes}
    return manifest


def runtime_manifest_path(args: argparse.Namespace, out_dir: Path, node_id: int) -> str:
    if args.compose or args.k8s:
        return f"/config/manifests/node-{node_id}-manifest.json"
    return str((out_dir / "manifests" / f"node-{node_id}-manifest.json").resolve())


def multiaddr_for_host(hostname: str, port: int, peer_id: str) -> str:
    try:
        ip = ipaddress.ip_address(hostname)
    except ValueError:
        prefix = "dns4"
    else:
        prefix = "ip6" if ip.version == 6 else "ip4"
    return f"/{prefix}/{hostname}/tcp/{port}/p2p/{peer_id}"


def build_node_args(
    node_id: int,
    args: argparse.Namespace,
    host_list: list[str] | None,
    manifest_arg_path: str | None,
) -> dict:
    """Build the CLI argument dict for a single node."""
    _, p2p_port, http_port = resolve_address(node_id, args, host_list)
    initial_validators = args.initial_validators or args.nodes

    node_args = {
        "id": node_id,
        "port": p2p_port,
        "http": http_port,
        "total-nodes": args.nodes,
        "initial-validators": initial_validators,
        "instances": args.instances,
        "batch-txs": args.batch_txs,
        "timeout-ms": args.timeout_ms,
        "inbound-msg-queue": DEFAULT_INBOUND_MSG_QUEUE,
        "inbound-tx-queue": DEFAULT_INBOUND_TX_QUEUE,
        "orderer-pending-cap": DEFAULT_ORDERER_PENDING_CAP,
        "consensus-topic": DEFAULT_CONSENSUS_TOPIC,
    }
    if manifest_arg_path:
        node_args["manifest"] = manifest_arg_path
    return node_args


def args_to_cli(node_args: dict) -> str:
    """Convert argument dict to CLI string."""
    parts = []
    for key, val in node_args.items():
        parts.append(f"-{key}={val}")
    return " ".join(parts)


def generate_peer_list(
    args: argparse.Namespace,
    host_list: list[str] | None,
    manifest: dict | None,
) -> list[dict]:
    """Generate the peer address list and valid multiaddrs when manifest data exists."""
    peers = []
    for i in range(args.nodes):
        hostname, p2p_port, http_port = resolve_address(i, args, host_list)
        manifest_node = None if manifest is None else manifest["nodes_by_id"].get(i)
        peer_id = "" if manifest_node is None else manifest_node.get("peer_id", "")
        multiaddr = ""
        if peer_id:
            multiaddr = multiaddr_for_host(hostname, p2p_port, peer_id)
        peers.append(
            {
                "node_id": i,
                "hostname": hostname,
                "p2p_port": p2p_port,
                "http_port": http_port,
                "p2p_address": f"{hostname}:{p2p_port}",
                "http_address": f"http://{hostname}:{http_port}",
                "peer_id": peer_id,
                "multiaddr": multiaddr,
            }
        )
    return peers


def validate_runtime_manifest_source_node(source_node: dict, peer: dict) -> None:
    node_id = peer["node_id"]
    required_public_fields = ["peer_id", "public_key_hex", "vrf_public_key_hex"]
    for field in required_public_fields:
        if not str(source_node.get(field, "")).strip():
            raise ValueError(f"manifest node {node_id} missing required field {field}")
    if not str(peer.get("multiaddr", "")).strip():
        raise ValueError(f"manifest node {node_id} missing derived p2p multiaddr")
    required_private_fields = ["private_key_hex", "vrf_private_key_hex"]
    for field in required_private_fields:
        if not str(source_node.get(field, "")).strip():
            raise ValueError(f"manifest node {node_id} missing required field {field}")



def write_runtime_manifests(out_dir: Path, manifest: dict, peers: list[dict]) -> Path:
    public_nodes = []
    manifests_dir = out_dir / "manifests"
    manifests_dir.mkdir(parents=True, exist_ok=True)

    for peer in peers:
        node_id = peer["node_id"]
        if node_id not in manifest["nodes_by_id"]:
            raise ValueError(f"manifest missing requested node {node_id}")
        source_node = manifest["nodes_by_id"][node_id]
        validate_runtime_manifest_source_node(source_node, peer)

        public_node = dict(source_node)
        public_node.pop("private_key_hex", None)
        public_node.pop("vrf_private_key_hex", None)
        if peer["multiaddr"]:
            public_node["p2p_multiaddr"] = peer["multiaddr"]
        public_nodes.append(public_node)

    cluster_manifest = {
        "version": manifest.get("version", 1),
        "nodes": public_nodes,
    }
    cluster_path = out_dir / "cluster-manifest.json"
    with open(cluster_path, "w", encoding="utf-8") as f:
        json.dump(cluster_manifest, f, indent=2)

    for local_node in public_nodes:
        runtime_nodes = []
        for peer_node in public_nodes:
            node_copy = dict(peer_node)
            if peer_node["id"] == local_node["id"]:
                source_node = manifest["nodes_by_id"][peer_node["id"]]
                node_copy["private_key_hex"] = source_node.get("private_key_hex", "")
                node_copy["vrf_private_key_hex"] = source_node.get("vrf_private_key_hex", "")
            runtime_nodes.append(node_copy)
        runtime_manifest = {
            "version": manifest.get("version", 1),
            "nodes": runtime_nodes,
        }
        path = manifests_dir / f"node-{local_node['id']}-manifest.json"
        with open(path, "w", encoding="utf-8") as f:
            json.dump(runtime_manifest, f, indent=2)

    return cluster_path


def main() -> int:
    args = parse_args()

    if args.nodes <= 0:
        print("ERROR: --nodes must be > 0", file=sys.stderr)
        return 1
    if args.nodes > 1 and not args.manifest:
        print(
            "ERROR: multi-node configuration requires --manifest with stable validator identities",
            file=sys.stderr,
        )
        return 1

    # Load host list for bare-metal mode
    host_list = None
    if args.hosts:
        hosts_path = Path(args.hosts)
        if not hosts_path.is_file():
            print(f"ERROR: hosts file not found: {args.hosts}", file=sys.stderr)
            return 1
        with open(hosts_path) as f:
            host_list = [
                line.strip() for line in f if line.strip() and not line.startswith("#")
            ]
        if not host_list:
            print("ERROR: hosts file is empty", file=sys.stderr)
            return 1
        print(f"Loaded {len(host_list)} hosts from {args.hosts}")

    manifest = None
    if args.manifest:
        try:
            manifest = load_manifest(args.manifest)
        except Exception as exc:
            print(f"ERROR: failed to load manifest: {exc}", file=sys.stderr)
            return 1
        if len(manifest["nodes_by_id"]) < args.nodes:
            print(
                f"ERROR: manifest has {len(manifest['nodes_by_id'])} nodes, need at least {args.nodes}",
                file=sys.stderr,
            )
            return 1

    # Create output directory
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    peers = generate_peer_list(args, host_list, manifest)
    cluster_manifest_path = None
    if manifest is not None:
        cluster_manifest_path = write_runtime_manifests(out_dir, manifest, peers)

    # ── Generate per-node configs ──────────────────────────────────────────
    all_args = []
    for i in range(args.nodes):
        manifest_arg_path = None
        if manifest is not None:
            manifest_arg_path = runtime_manifest_path(args, out_dir, i)
        node_args = build_node_args(i, args, host_list, manifest_arg_path)
        all_args.append(node_args)

    # Write individual node argument files
    nodes_dir = out_dir / "nodes"
    nodes_dir.mkdir(parents=True, exist_ok=True)
    for i, na in enumerate(all_args):
        node_file = nodes_dir / f"node-{i}.args"
        with open(node_file, "w") as f:
            f.write(args_to_cli(na) + "\n")

    # ── Generate peer list ─────────────────────────────────────────────────

    peers_file = out_dir / "peers.json"
    with open(peers_file, "w") as f:
        json.dump(peers, f, indent=2)

    # Also write a flat peers.txt for shell scripts
    peers_txt = out_dir / "peers.txt"
    with open(peers_txt, "w") as f:
        for p in peers:
            f.write(
                f"{p['node_id']} {p['hostname']} {p['p2p_port']} {p['http_port']}\n"
            )

    # ── Generate HTTP endpoint list (for benchmarks / metrics) ─────────────
    endpoints_file = out_dir / "http_endpoints.txt"
    with open(endpoints_file, "w") as f:
        for p in peers:
            f.write(p["http_address"] + "\n")

    # ── Generate docker-compose override (compose mode only) ───────────────
    if args.compose:
        compose_file = out_dir / "docker-compose-generated.yml"
        _write_compose(
            compose_file,
            all_args,
            args,
            out_dir if cluster_manifest_path is not None else None,
        )

    # ── Generate K8s configmap patch (k8s mode) ────────────────────────────
    if args.k8s:
        cm_file = out_dir / "configmap-patch.yaml"
        _write_k8s_configmap_patch(cm_file, args)

    # ── Summary ────────────────────────────────────────────────────────────
    mode = "k8s" if args.k8s else ("compose" if args.compose else "bare-metal")
    print(f"\n{'=' * 60}")
    print("  Evolv-BFT Configuration Generated")
    print(f"{'=' * 60}")
    print(f"  Mode:              {mode}")
    print(f"  Nodes:             {args.nodes}")
    print(f"  Instances/node:    {args.instances}")
    print(f"  Batch TXs:         {args.batch_txs}")
    print(f"  Timeout (ms):      {args.timeout_ms}")
    print(f"  Output dir:        {out_dir.resolve()}")
    print(f"  Per-node args:     {nodes_dir}/node-{{0..{args.nodes - 1}}}.args")
    print(f"  Peer list (JSON):  {peers_file}")
    print(f"  Peer list (txt):   {peers_txt}")
    print(f"  HTTP endpoints:    {endpoints_file}")
    if cluster_manifest_path is not None:
        print(f"  Cluster manifest:  {cluster_manifest_path}")
    if args.compose:
        print(f"  Compose file:      {out_dir / 'docker-compose-generated.yml'}")
    if args.k8s:
        print(f"  ConfigMap patch:   {out_dir / 'configmap-patch.yaml'}")
    print(f"{'=' * 60}\n")

    return 0


def _write_compose(
    path: Path,
    all_args: list[dict],
    args: argparse.Namespace,
    config_mount_dir: Path | None,
) -> None:
    """Generate a Docker Compose file for N nodes."""
    services = {}
    for na in all_args:
        nid = na["id"]
        svc_name = f"{args.compose_prefix}-{nid}"
        volumes = [
            f"evolvbft-data-{nid}:/data",
        ]
        if config_mount_dir is not None:
            volumes.append(f"{config_mount_dir.resolve()}:/config:ro")
        services[svc_name] = {
            "image": "evolvbft:latest",
            "container_name": svc_name,
            "command": args_to_cli(na),
            "ports": [
                f"{args.http_base_port + nid}:{na['http']}",
            ],
            "networks": ["evolvbft-net"],
            "restart": "unless-stopped",
            "volumes": volumes,
        }

    compose = {
        "version": "3.8",
        "services": services,
        "networks": {
            "evolvbft-net": {
                "driver": "bridge",
            },
        },
        "volumes": {f"evolvbft-data-{na['id']}": {} for na in all_args},
    }

    with open(path, "w") as f:
        # Use json for deterministic output, then convert to YAML-like
        # (We write raw YAML manually to avoid PyYAML dependency)
        json.dump(compose, f, indent=2)
    print(f"  (Docker Compose config written as JSON → {path})")


def _write_k8s_configmap_patch(path: Path, args: argparse.Namespace) -> None:
    """Generate a K8s ConfigMap patch for the cluster size."""
    initial_validators = args.initial_validators or args.nodes
    content = f"""# Auto-generated ConfigMap patch for {args.nodes} nodes
# Apply with: kubectl patch configmap evolvbft-config --patch-file {path.name}
apiVersion: v1
kind: ConfigMap
metadata:
  name: evolvbft-config
  namespace: {args.k8s_namespace}
data:
  EVOLVBFT_TOTAL_NODES: "{args.nodes}"
  EVOLVBFT_INITIAL_VALIDATORS: "{initial_validators}"
  EVOLVBFT_INSTANCES: "{args.instances}"
  EVOLVBFT_BATCH_TXS: "{args.batch_txs}"
  EVOLVBFT_TIMEOUT_MS: "{args.timeout_ms}"
  EVOLVBFT_INBOUND_MSG_QUEUE: "{DEFAULT_INBOUND_MSG_QUEUE}"
  EVOLVBFT_INBOUND_TX_QUEUE: "{DEFAULT_INBOUND_TX_QUEUE}"
  EVOLVBFT_ORDERER_PENDING_CAP: "{DEFAULT_ORDERER_PENDING_CAP}"
  EVOLVBFT_P2P_PORT: "{args.base_port}"
  EVOLVBFT_HTTP_PORT: "{args.http_base_port}"
  EVOLVBFT_CONSENSUS_TOPIC: "{DEFAULT_CONSENSUS_TOPIC}"
  EVOLVBFT_HEADLESS_SVC: "{args.k8s_svc_name}.{args.k8s_namespace}.svc.cluster.local"
"""
    with open(path, "w") as f:
        f.write(content)


if __name__ == "__main__":
    sys.exit(main())
