// Code generated by hand from sfac.proto; DO NOT EDIT by hand.
// This follows the same pattern as network/proto/consensus_mock.go.

package proto

import (
	"context"

	"google.golang.org/grpc"
)

// ─── Message types ──────────────────────────────────────────────────────────

type SFACRequest struct {
	Epoch        uint64                 `json:"epoch"`
	NumInstances int32                  `json:"num_instances"`
	Instances    []*SFACInstanceRequest `json:"instances"`
	GlobalState  []float64              `json:"global_state,omitempty"`
}

type SFACInstanceRequest struct {
	InstanceID     uint64              `json:"instance_id"`
	ValidatorCount int32               `json:"validator_count"`
	FaultCount     int32               `json:"fault_count"`
	Throughput     float64             `json:"throughput"`
	Latency        float64             `json:"latency"`
	ViewChanges    int32               `json:"view_changes"`
	TrustFeatures  []*SFACTrustFeature `json:"trust_features"`
}

type SFACTrustFeature struct {
	AgentID          uint64  `json:"agent_id"`
	TimeoutRate      float64 `json:"timeout_rate"`
	EquivocationRate float64 `json:"equivocation_rate"`
	ViewChangeRate   float64 `json:"view_change_rate"`
	MeanLatency      float64 `json:"mean_latency"`
	StdLatency       float64 `json:"std_latency"`
}

type SFACResponse struct {
	Actions []*SFACAgentAction `json:"actions"`
	Value   float64            `json:"value,omitempty"`
}

type SFACAgentAction struct {
	InstanceID uint64    `json:"instance_id"`
	Reconfig   []int32   `json:"reconfig"`
	Rotate     bool      `json:"rotate"`
	Params     []float64 `json:"params"`
}

type TrajectorySample struct {
	Epoch               uint64             `json:"epoch"`
	Observation         []float64          `json:"observation"`
	Action              []float64          `json:"action"`
	Reward              float64            `json:"reward"`
	PerInstanceRewards  []float64          `json:"per_instance_rewards"`
	RoleRewards         map[string]float64 `json:"role_rewards,omitempty"`
	NextObservation     []float64          `json:"next_observation"`
	Done                bool               `json:"done"`
}

type ResetRequest struct {
	Epoch uint64 `json:"epoch"`
}

type SFACAck struct {
	Success bool   `json:"success"`
	Error   string `json:"error,omitempty"`
}

type HealthRequest struct{}

type HealthResponse struct {
	Ready           bool   `json:"ready"`
	ModelVersion    string `json:"model_version"`
	DecisionsServed int64  `json:"decisions_served"`
}

// ─── gRPC service interfaces ────────────────────────────────────────────────

// SFACServiceServer is the server-side interface (implemented by Python via grpcio).
type SFACServiceServer interface {
	Decide(context.Context, *SFACRequest) (*SFACResponse, error)
	Feedback(context.Context, *TrajectorySample) (*SFACAck, error)
	Reset(context.Context, *ResetRequest) (*SFACAck, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
}

// SFACServiceClient is the client-side interface (used by Go adaptive controller).
type SFACServiceClient interface {
	Decide(ctx context.Context, in *SFACRequest, opts ...grpc.CallOption) (*SFACResponse, error)
	Feedback(ctx context.Context, in *TrajectorySample, opts ...grpc.CallOption) (*SFACAck, error)
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*SFACAck, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

// ─── Client implementation ──────────────────────────────────────────────────

type sfacServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSFACServiceClient(cc grpc.ClientConnInterface) SFACServiceClient {
	return &sfacServiceClient{cc}
}

func (c *sfacServiceClient) Decide(ctx context.Context, in *SFACRequest, opts ...grpc.CallOption) (*SFACResponse, error) {
	out := new(SFACResponse)
	err := c.cc.Invoke(ctx, "/adaptive.SFACService/Decide", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sfacServiceClient) Feedback(ctx context.Context, in *TrajectorySample, opts ...grpc.CallOption) (*SFACAck, error) {
	out := new(SFACAck)
	err := c.cc.Invoke(ctx, "/adaptive.SFACService/Feedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sfacServiceClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*SFACAck, error) {
	out := new(SFACAck)
	err := c.cc.Invoke(ctx, "/adaptive.SFACService/Reset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sfacServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/adaptive.SFACService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ─── Server registration ────────────────────────────────────────────────────

func RegisterSFACServiceServer(s grpc.ServiceRegistrar, srv SFACServiceServer) {
	s.RegisterService(&SFACService_ServiceDesc, srv)
}

func _SFACService_Decide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SFACRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SFACServiceServer).Decide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/adaptive.SFACService/Decide"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SFACServiceServer).Decide(ctx, req.(*SFACRequest))
	})
}

func _SFACService_Feedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrajectorySample)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SFACServiceServer).Feedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/adaptive.SFACService/Feedback"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SFACServiceServer).Feedback(ctx, req.(*TrajectorySample))
	})
}

func _SFACService_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SFACServiceServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/adaptive.SFACService/Reset"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SFACServiceServer).Reset(ctx, req.(*ResetRequest))
	})
}

func _SFACService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SFACServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/adaptive.SFACService/Health"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SFACServiceServer).Health(ctx, req.(*HealthRequest))
	})
}

var SFACService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adaptive.SFACService",
	HandlerType: (*SFACServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "Decide", Handler: _SFACService_Decide_Handler},
		{MethodName: "Feedback", Handler: _SFACService_Feedback_Handler},
		{MethodName: "Reset", Handler: _SFACService_Reset_Handler},
		{MethodName: "Health", Handler: _SFACService_Health_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sfac.proto",
}
